name: CI testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  pytest:
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade --user pip
          pip install torch==1.8.1+cpu torchvision==0.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html --quiet
          pip install -r tests/requirements.txt --quiet
          python --version
          pip --version
          pip list
        shell: bash

      - name: Tests
        run: |
          python -m pytest -v