name: CI testing

on:
  push: {}
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --quiet
          pip install -r tests/requirements.txt --quiet
          python --version
          pip --version
          pip list
        shell: bash

      - name: Tests
        run: |
          python -m pytest -v